main.o:main.c
	gcc -c main.c
main.exe:main.o
	gcc main.o -o main  
	
m1.o:m1.c
	gcc -c m1.c
m1.exe:m1.o
	gcc m1.o -o m1	
	
m2.o:m2.c
	gcc -c m2.c
m2.exe:m2.o
	gcc -c m2.c
	
m3.o:m3.c
	gcc -c m3.c
m3.exe:m3.o
	gcc -c m3.c
				
			
		      
        
